Library Text Processing

String

In [2]:
testString = "dicoding"

In [3]:
testString.upper()

'DICODING'

In [4]:
testString.lower()

'dicoding'

In [5]:
testString.title()

'Dicoding'

In [6]:
testString.split("i")

['d', 'cod', 'ng']

In [7]:
testString.zfill(20)

'000000000000dicoding'

Regex
>untuk mencari teks berdasarakn pola tertentu

In [8]:
import re     # Import modul regex
 
pola= '^a...s$'
string_tes= 'abyss'
hasil= re.match(pola, string_tes)
 
if hasil:
    print("Pencarian berhasil.")
else:
    print("Pencarian gagal.") 

Pencarian berhasil.


Library Matematika

In [9]:
import math

print(math.sqrt(25)) 
print(math.pi) 

5.0
3.141592653589793


Library Data Processing

Pandas
> Library ini menyediakan struktur data dan alat untuk membantu pengguna dalam melakukan manipulasi, pembersihan, transformasi, dan analisis data dengan mudah dan efisien.

In [3]:
import pandas as pd

#membuat DataFrame dari dictionary
data = {
    'Nama': ['John', 'Jane', 'Bob', 'Alice'],
    'Usia': [25, 30, 22,28],
    'Pekerjaan': ['Engineeer', 'Teacher', 'Designer', 'Doctor']
}

df = pd.DataFrame(data)

#menampilkan DataFrame
print(df)

    Nama  Usia  Pekerjaan
0   John    25  Engineeer
1   Jane    30    Teacher
2    Bob    22   Designer
3  Alice    28     Doctor


NumPy
> untuk scientific computing pada Python. Library ini menyediakan objek array multidimensi, berbagai jenis objek lainnya, seperti masked array dan matrix, dan sebagainya.

In [4]:
import numpy

matriks = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print(matriks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Matplotlib

In [ ]:
import matplotlib.pyplot as plt
 
# Data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
 
# Membuat plot garis
plt.plot(x, y)
 
# Menambahkan judul dan label sumbu
plt.title("Contoh Plot Garis")
plt.xlabel("Sumbu X")
plt.ylabel("Sumbu Y")
 
# Menampilkan plot
plt.show()

Seaborn

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
 
# Contoh data
tips = sns.load_dataset('tips')  # Memuat dataset tips dari Seaborn
 
# Contoh plot histogram
sns.histplot(tips['total_bill'], kde=True)
plt.title('Histogram Total Bill')
plt.xlabel('Total Bill')
plt.ylabel('Frequency')
plt.show()

Library File Management

OS
> berguna untuk fungsi-fungsi yang berkaitan dengan sistem operasi, misalnya open(), path(), getcwd(), dan fungsi lainnya. Modul ini memungkinkan Anda untuk memanfaatkan fungsi yang sama dan mengeksekusi fungsi terkait OS yang mungkin berbeda dalam setiap sistem operasi. 

In [3]:
import os
print(os.getcwd())

d:\Online Course\Dicoding\dbsDicodingML\learnData\Library


Library Web Scraping

Beautifulsoup

In [4]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
 
# Pengambilan konten
url = "http://python.org/"
page = urlopen(url)
html = page.read().decode("utf-8")
 
# Membuat objek BeautifulSoup
soup = BeautifulSoup(html, "html.parser")
 
# Mencetak judul halaman
print(soup.title)

<title>Welcome to Python.org</title>


Urllib
> bertujuan untuk scraping konten dari sebuah website. Penggunaan urllib berbeda dengan beautifulsoup. 

In [5]:
from urllib.request import urlopen
 
# Pengambilan konten
url = "http://python.org/"
page = urlopen(url)
html = page.read().decode("utf-8")
 
# Mencari indeks awal dan akhir
start_index = html.find("<title>") + len("<title>")
end_index = html.find("</title>")
 
# Mengekstrak dan mencetak judul halaman
title = html[start_index:end_index]
print(title)

Welcome to Python.org


Library Machine Learning

1. scikit-learn
>menyediakan berbagai algoritma pemelajaran mesin siap pakai untuk membantu dalam pengembangan model pemelajaran mesin, pemrosesan data, dan evaluasi kinerja model.
2. TensorFlow
>mengembangkan machine learning hingga tahap deployment.
3. PyTorch
>dikembangkan oleh Facebook’s AI Research lab (FAIR). PyTorch menyediakan alat dan kerangka kerja yang kuat untuk mengembangkan model pemelajaran mesin, terutama dalam konteks jaringan saraf tiruan (neural networks).