Library Text Processing

String

In [2]:
testString = "dicoding"

In [3]:
testString.upper()

'DICODING'

In [4]:
testString.lower()

'dicoding'

In [5]:
testString.title()

'Dicoding'

In [6]:
testString.split("i")

['d', 'cod', 'ng']

In [7]:
testString.zfill(20)

'000000000000dicoding'

Regex
>untuk mencari teks berdasarakn pola tertentu

In [8]:
import re     # Import modul regex
 
pola= '^a...s$'
string_tes= 'abyss'
hasil= re.match(pola, string_tes)
 
if hasil:
    print("Pencarian berhasil.")
else:
    print("Pencarian gagal.") 

Pencarian berhasil.


Library Matematika

In [9]:
import math

print(math.sqrt(25)) 
print(math.pi) 

5.0
3.141592653589793


Library Data Processing

Pandas
> Library ini menyediakan struktur data dan alat untuk membantu pengguna dalam melakukan manipulasi, pembersihan, transformasi, dan analisis data dengan mudah dan efisien.

In [3]:
import pandas as pd

#membuat DataFrame dari dictionary
data = {
    'Nama': ['John', 'Jane', 'Bob', 'Alice'],
    'Usia': [25, 30, 22,28],
    'Pekerjaan': ['Engineeer', 'Teacher', 'Designer', 'Doctor']
}

df = pd.DataFrame(data)

#menampilkan DataFrame
print(df)

    Nama  Usia  Pekerjaan
0   John    25  Engineeer
1   Jane    30    Teacher
2    Bob    22   Designer
3  Alice    28     Doctor


NumPy
> untuk scientific computing pada Python. Library ini menyediakan objek array multidimensi, berbagai jenis objek lainnya, seperti masked array dan matrix, dan sebagainya.

In [4]:
import numpy

matriks = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print(matriks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
